[agent]
# Интервал отправки метрик в секундах. Чем меньше - тем больше нагрузка на систему
send_metrics_interval = 5

[server]
# Уникальный ключ авторизации вашего сервера
server_key = "your_generated_token"
# Куда будут отправляться данные (API сервер или напрямую в дешборд)
server_url = "http://persona-rs.com/metrics"

[metrics.disks]
enabled = true
# Не будет считать диски докера
mount_points = [ "/" ]
filter = { only = [], enabled = false }

[metrics.cpu]
enabled = true
filter = { expect = [], enabled = false}

[metrics.system]
enabled = true

[metrics.network]
enabled = true