[agent]
# Интервал отправки метрик в секундах. Чем меньше - тем больше нагрузка на систему
send_metrics_interval = 5
debug_mode = false

[server]
# Уникальный ключ авторизации вашего сервера
server_key = "your_generated_token"
# Куда будут отправляться данные (API сервер или напрямую в дешборд)
server_url = "http://persona-rs.com/metrics"

[metrics.components]
enabled = true

[metrics.disks]
enabled = true

[metrics.cpu]
enabled = true

[metrics.system]
enabled = true

[metrics.network]
enabled = true