name: Checkout And Install Rust

inputs:
  build_target:
    required: false
    default: ''
    type: string

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ inputs.build_target }}